# Generated by Django 5.0.4 on 2024-04-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=200)),
                ('bed_type', models.CharField(max_length=200)),
                ('occupancy', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=200)),
                ('view', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
